// Generated by tools/contract.py in anker-prime-ble. Do not edit.
//
// The Python modules in that repository are the source of truth — they carry the
// evidence for every field in their comments. This file is a projection of their
// constants so a Swift implementation cannot drift from them silently.
//
// Constants are the easy half. For the decoding *behaviour*, replay
// spec/fixtures/*.json and compare field by field; that is what catches the
// mistakes that matter.

import Foundation

public enum AnkerPrimeSpec {
    public enum Transport {
        public static let serviceUUID = "8C850001-0302-41C5-B46E-CF057C562025"
        public static let writeCharacteristicUUID = "8C850002-0302-41C5-B46E-CF057C562025"
        public static let notifyCharacteristicUUID = "8C850003-0302-41C5-B46E-CF057C562025"
        public static let advertisedServiceUUID = "0000FF09-0000-1000-8000-00805F9B34FB"

        public static let initialKey = Data([0xB8, 0xFF, 0x74, 0x22, 0x95, 0x5D, 0x4E, 0xB6, 0xD5, 0x54, 0xA2, 0xC4, 0x70, 0x28, 0x05, 0x59])
        public static let initialIV = Data([0x6B, 0xA3, 0xE3, 0xF2, 0xF3, 0xA6, 0x0F, 0x29, 0x71, 0xCE, 0x5D, 0x1F])
        public static let gcmAAD = Data([0x33, 0x22, 0x11, 0x00, 0x77, 0x66, 0x55, 0x44, 0xBB, 0xAA, 0x99, 0x88, 0xFF, 0xEE, 0xDD, 0xCC])

        public static let flagEncrypted: UInt8 = 0x40
        public static let flagAcknowledged: UInt8 = 0x08
        public static let groupSession: UInt8 = 0x01
        public static let groupTelemetry: UInt8 = 0x0F
        public static let commandStatus: UInt16 = 0x0200
        public static let commandRealtime: UInt16 = 0x020A
    }

    public enum Charger {
        public static let namePrefix = "ASHDJW"
        public static let needsAccountID = true
        public static let needsRealtimeProbe = true
        public static let ports = ["C1", "C2", "C3"]
        public static let realtimeCommands: Set<UInt16> = [0x0206, 0x0207, 0x020A, 0x0300, 0x0303, 0x0410, 0x4300]
        public static let snapshotCommands: Set<UInt16> = [0x0040, 0x0200, 0x0405, 0x0A00]

        // Voltage is millivolts, current milliamps, power centiwatts — unlike the
        // power bank, which is tenths throughout.
        public static let portStructTLV: [UInt8: String] = [
            165: "C1",
            166: "C2",
            167: "C3",
        ]
        public static let portCableTLV: [UInt8: String] = [
            172: "C1",
            173: "C2",
            174: "C3",
        ]
        public static let identityTLV: UInt8 = 0xB4
        public static let brandModelTLV: UInt8 = 0xB5
        public static let identitySentinels: Set<UInt16> = [0x0000, 0xFFFA, 0xFFFB, 0xFFFC, 0xFFFD, 0xFFFE, 0xFFFF]

        public static let cableCapabilityLabels: [String: String] = [
            "00": "3A-60W MAX",
            "01": "5A-100W MAX",
            "02": "EPR-240W MAX",
        ]
        public static let chargingInfoLabels: [String: String] = [
            "01": "Apple PD Fast Charging",
            "02": "Samsung Fast Charging",
            "03": "Samsung Super Fast Charging",
        ]

        public static let vendorNames: [UInt16: String] = [
        0x05AC: "Apple",
        0x04E8: "Samsung",
        0x2717: "Xiaomi",
        0x12D1: "Huawei",
        0x18D1: "Google",
        0x1004: "LG",
        0x0451: "Texas Instruments",
        0x291A: "Anker",
        0x03F0: "HP",
        0x413C: "Dell",
        0x17EF: "Lenovo",
        0x045E: "Microsoft",
        0x0B05: "ASUS",
        0x0DB0: "MSI",
        0x1532: "Razer",
        ]

        public static let deviceModels: [UInt32: String] = [
        modelKey(0x05AC, 0x7519): "iPhone 17 series",
        modelKey(0x05AC, 0x7319): "MacBook Pro series",
        modelKey(0x05AC, 0x7117): "iPad Pro series",
        modelKey(0x291A, 0x110B): "20K Prime Power Bank",
        ]

        public static let brandCodes: [UInt8: String] = [
        0x01: "Apple",
        0x02: "Samsung",
        0x03: "Xiaomi",
        0x04: "Huawei",
        0x05: "Google",
        0x06: "LG",
        0x07: "IDT",
        0x08: "TI",
        0x09: "YBZ",
        0x0A: "Anker",
        0x0B: "Honor",
        0x0C: "HP",
        0x0D: "Dell",
        0x0E: "Lenovo",
        0x0F: "Microsoft",
        0x10: "ASUS",
        0x11: "ASUS",
        0x12: "MSI",
        0x13: "Razer",
        ]

        public static func modelKey(_ vendor: UInt16, _ product: UInt16) -> UInt32 {
            (UInt32(vendor) << 16) | UInt32(product)
        }
    }

    public enum PowerBank {
        public static let needsAccountID = true
        public static let needsRealtimeProbe = false
        public static let ports = ["C1", "C2", "A"]
        public static let realtimeCommands: Set<UInt16> = [0x0300]
        public static let snapshotCommands: Set<UInt16> = [0x0200]

        // Volts, amps and watts are all u16 little-endian in tenths.
        public static let stateTLV: UInt8 = 0xA1
        public static let batteryTLV: UInt8 = 0xA2
        public static let timeLeftTLV: UInt8 = 0xA3
        public static let thermalStateTLV: UInt8 = 0xA4
        public static let inputTotalTLV: UInt8 = 0xA5
        public static let outputTotalTLV: UInt8 = 0xA6
        public static let dockTLV: UInt8 = 0xA7
        public static let portC1TLV: UInt8 = 0xA8
        public static let portC2TLV: UInt8 = 0xA9
        public static let portATLV: UInt8 = 0xAC
        public static let temperature1TLV: UInt8 = 0xAF
        public static let temperature2TLV: UInt8 = 0xB0

        // The realtime block appears inside the 0x0200 snapshot at +0x0D.
        public static let snapshotShift: UInt8 = 13
        public static let snapshotStateTLV: UInt8 = 0xA1
        public static let snapshotBatteryTLV: UInt8 = 0xA6
        public static let snapshotTimeLeftTLV: UInt8 = 0xA7
        public static let snapshotPomodoroSecondsTLV: UInt8 = 0xAC
        public static let snapshotPomodoroEnableTLV: UInt8 = 0xE2

        /// Byte 8 of a C-port block: a cable is in the port, negotiated or not.
        public static let attachFlagOffset = 8
        public static let attachFlagPresent: UInt8 = 0x07
        /// Byte 7: 0x02 while the port is sourcing, 0xFF while drawing in or idle.
        public static let sourceRoleOffset = 7
        public static let sourceRoleSourcing: UInt8 = 0x02

        /// The per-port power slot keeps its last value when a port goes idle.
        /// Read it only when the mode byte is non-zero.
        public static let powerSlotIsSticky = true
    }
}
